### ISSUE TITLE
module not installed

### ISSUE THREAD

**Issue by Pilly170** [RhinoSecurityLabs/pacu#121]
Run the install script, then ran the script, also tried installing the module manually.

python3 pacu.py 
Traceback (most recent call last):
  File "pacu.py", line 21, in <module>
    import boto3
  File "/opt/Cloud/AWS/pacu/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/opt/Cloud/AWS/pacu/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/opt/Cloud/AWS/pacu/botocore/session.py", line 27, in <module>
    import botocore.client
  File "/opt/Cloud/AWS/pacu/botocore/client.py", line 16, in <module>
    from botocore import waiter, xform_name
  File "/opt/Cloud/AWS/pacu/botocore/waiter.py", line 13, in <module>
    import jmespath
<class 'ModuleNotFoundError'>: No module named 'jmespath'

Pacu was not able to start because a required Python package was not found.
Run `sh install.sh` to check and install Pacu's Python requirements.

sudo pip install jmespath
Requirement already satisfied: jmespath in /root/.local/lib/python2.7/site-packages (0.9.3)

**Comment by SpenGietz** [comment]
There are a couple possibilities here.

- Looks like you may be running pip2 to try and install it, so you could try running `pip3 install jmespath` or `python3 -m pip install jmespath`.
- Or the folder that jmespath is installed in is not in your PYTHONPATH (https://stackoverflow.com/questions/3402168/permanently-add-a-directory-to-pythonpath)

Let me know if either of those work for you. I believe it has to do with PYTHONPATH because jmespath should auto install.
