### ISSUE TITLE
SQLITE error

### ISSUE THREAD

**Issue by random-robbie** [RhinoSecurityLabs/pacu#124]
**Describe the bug**
```
Pacu (decathalon:dec) > whoami
```

[2018-11-13 09:50:21] Pacu encountered an error while running the previous command. Check sessions/decathalon/error_log.txt for technical details. [LOG LEVEL: MINIMAL]

    <class 'sqlalchemy.exc.OperationalError'>: (sqlite3.OperationalError) no such column: aws_key.role_name [SQL: 'SELECT aws_key.id AS aws_key_id, aws_key.session_id AS aws_key_session_id, aws_key.user_name AS aws_key_user_name, aws_key.role_name AS aws_key_role_name, aws_key.arn AS aws_key_arn, aws_key.account_id AS aws_key_account_id, aws_key.user_id AS aws_key_user_id, aws_key.roles AS aws_key_roles, aws_key.groups AS aws_key_groups, aws_key.policies AS aws_key_policies, aws_key.access_key_id AS aws_key_access_key_id, aws_key.secret_access_key AS aws_key_secret_access_key, aws_key.session_token AS aws_key_session_token, aws_key.key_alias AS aws_key_key_alias, aws_key.permissions_confirmed AS aws_key_permissions_confirmed, aws_key.allow_permissions AS aws_key_allow_permissions, aws_key.deny_permissions AS aws_key_deny_permissions \nFROM aws_key \nWHERE aws_key.session_id = ? AND aws_key.key_alias = ?'] [parameters: (20, 'dec')] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**To Reproduce**
Steps to reproduce the behavior:
1. whoami


**Expected behavior**
to list the IAM role details


**Operating System (please complete the following information):**
 - OS Ubuntu 18.04]
 - Python version:.3.5

**Error log**
```
[2018-11-13 09:50:23] (decathalon): 
Traceback (most recent call last):
  File "pacu.py", line 1676, in run
    self.idle()
  File "pacu.py", line 1609, in idle
    self.parse_command(command)
  File "pacu.py", line 504, in parse_command
    self.parse_data_command(command)
  File "pacu.py", line 577, in parse_data_command
    session.print_all_data_in_session()
  File "/tmp/pacu/core/models.py", line 199, in print_all_data_in_session
    owned_keys = column.value.all()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2783, in all
    return list(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/dynamic.py", line 247, in __iter__
    return iter(self._clone(sess))
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2935, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2958, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
<class 'sqlalchemy.exc.OperationalError'>: (sqlite3.OperationalError) no such column: aws_key.role_name [SQL: 'SELECT aws_key.id AS aws_key_id, aws_key.session_id AS aws_key_session_id, aws_key.user_name AS aws_key_user_name, aws_key.role_name AS aws_key_role_name, aws_key.arn AS aws_key_arn, aws_key.account_id AS aws_key_account_id, aws_key.user_id AS aws_key_user_id, aws_key.roles AS aws_key_roles, aws_key.groups AS aws_key_groups, aws_key.policies AS aws_key_policies, aws_key.access_key_id AS aws_key_access_key_id, aws_key.secret_access_key AS aws_key_secret_access_key, aws_key.session_token AS aws_key_session_token, aws_key.key_alias AS aws_key_key_alias, aws_key.permissions_confirmed AS aws_key_permissions_confirmed, aws_key.allow_permissions AS aws_key_allow_permissions, aws_key.deny_permissions AS aws_key_deny_permissions \nFROM aws_key \nWHERE ? = aws_key.session_id'] [parameters: (20,)] (Background on this error at: http://sqlalche.me/e/e3q8
```

**Comment by SpenGietz** [comment]
Sorry for the delayed response here.

My guess on what happened is that you had Pacu installed, used it, then updated it to an update where the database structure was modified. 

Currently there isn't a feature to "fast-forward" the database on updates like those, so I try to make them as little as possible, but what I would suggest is deleting/renaming your current SQLite DB and starting Pacu again so it can generate a new one.

This is something we are aware of as a problem and will likely be fixed along with a new type of local database sometime in the future.

**Comment by andresriancho** [comment]
Just triggered the same issue. I believe it will be common as the project gets more updates. Maybe consider applying DB migrations when old DBs are used? Maybe consider a better error message that doesn't require users to search for this issue?
