### ISSUE TITLE
iam__privesc_scan not running all potential escalation methods

### ISSUE THREAD

**Issue by nmarchini** [RhinoSecurityLabs/pacu#138]
**Bug Description**
When running iam__privesc_scan it attempts the first escalation method but then doesn't perform any more. The only method that gets executed is CreateNewPolicyVersion, once this is complete it tries SetExistingDefaultPolicyVersion but then gos back to a prompt (Is there a specific policy you want to target?)

**To Reproduce**
1. run iam__privesc_scan
2. No permissions detected yet message appears so hit Y to run module "iam__enum_permissions" to fetch them
3. Enter the policy to target

**Expected behavior**
The module continues through all of the 22 methods of escalation.

**Screenshots**
[https://gist.github.com/nmarchini/b99923987721632e50192810d67c137a#file-gistfile1-txt](url)

**Operating System (please complete the following information):**
 - Mac OS 10.14.4
 - Python version: 

**Error log**
[2019-04-08 21:45:11] (session2): 
Traceback (most recent call last):
  File "pacu.py", line 1680, in run
    self.idle()
  File "pacu.py", line 1613, in idle
    self.parse_command(command)
  File "pacu.py", line 516, in parse_command
    self.parse_exec_module_command(command)
  File "pacu.py", line 858, in parse_exec_module_command
    self.exec_module(command)
  File "pacu.py", line 1087, in exec_module
    summary_data = module.main(command[2:], self)
  File "/Users/user.name/OneDrive - Acme/scratch/pacu/modules/iam__privesc_scan/main.py", line 583, in main
    response = methods[potential_method](pacu_main, print, input, fetch_data)
  File "/Users/user.name/OneDrive - Acme/scratch/pacu/modules/iam__privesc_scan/main.py", line 816, in SetExistingDefaultPolicyVersion
    PolicyArn=policy_arn
  File "/Users/user.name/OneDrive - Acme/scratch/pacu/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/user.name/OneDrive - Acme/scratch/pacu/botocore/client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/user.name/OneDrive - Acme/scratch/pacu/botocore/client.py", line 621, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/user.name/OneDrive - Acme/scratch/pacu/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
<class 'botocore.exceptions.ParamValidationError'>: Parameter validation failed:
Invalid length for parameter PolicyArn, value: 4, valid range: 20-inf

**Comment by MBlagui** [comment]
Also when running iam__privesc_scan. My ec2 role have *:* permission but is limited by SCP so it's saying ok admin:

> [iam__privesc_scan] You already have admin permissions (Action: * on Resource: *)! Exiting...

While this is not the case. I would like to enumerate what permission I really still have.

**Comment by SpenGietz** [comment]
This should be resolved now, so I'm closing it, but let me know if not!

@MBlagui It will say that because in a lot of scenarios it will be unable to determine if there are any SCPs in place. You'd only be able to enumerate the SCP if you were within the Organization Master account afaik
