### ISSUE TITLE
<class 'KeyError'>: 'url' 

### ISSUE THREAD

**Issue by matesio** [RhinoSecurityLabs/pacu#146]
I'm getting **<class 'KeyError'>: 'url'** while trying to download AWS inspector report using the following command

` run inspector__get_reports --download-reports`

**OS**: Linux mint 19.2 tina
**Python**: 3.6.8
---------------------------
pacu console output
---------------------------
[inspector__get_reports]   Report saved to: sessions/Session_name/downloads/inspector_assessments/0-XYZ.html
[inspector__get_reports]   Report saved to: sessions/Session_name/downloads/inspector_assessments/0-ABC.html

[2019-08-20 08:28:16] Pacu encountered an error while running the previous command. Check sessions/Session_name/error_log.txt for technical details. [LOG LEVEL: MINIMAL]

    <class 'KeyError'>: 'url'

-----------
error.log
-----------
Traceback (most recent call last):
  File "pacu.py", line 1704, in run
    self.idle()
  File "pacu.py", line 1637, in idle
    self.parse_command(command)
  File "pacu.py", line 518, in parse_command
    self.parse_exec_module_command(command)
  File "pacu.py", line 879, in parse_exec_module_command
    self.exec_module(command)
  File "pacu.py", line 1109, in exec_module
    summary_data = module.main(command[2:], self)
  File "/home/hammad/pacu/pacu/modules/inspector__get_reports/main.py", line 73, in main
    with urllib.request.urlopen(response['url']) as response, open(file_name, 'a') as out_file:
<class 'KeyError'>: 'url'

**Comment by SpenGietz** [comment]
Turns out it was failing because the reports can fail to generate. I just pushed a fix to output an error and move on!
