### ISSUE TITLE
ReadTimeoutError on iam__bruteforce_permissions

### ISSUE THREAD

**Issue by andresriancho** [RhinoSecurityLabs/pacu#148]
**Describe the bug**
Got incorrect import while running `iam__bruteforce_permissions`

**To Reproduce**
1. Run the command `run iam__bruteforce_permissions`

**Expected behavior**
No errors.

**Screenshots**
```
Traceback (most recent call last):
  File "pacu.py", line 1704, in run
    self.idle()
  File "pacu.py", line 1639, in idle
    self.idle()
  File "pacu.py", line 1637, in idle
    self.parse_command(command)
  File "pacu.py", line 518, in parse_command
    self.parse_exec_module_command(command)
  File "pacu.py", line 879, in parse_exec_module_command
    self.exec_module(command)
  File "pacu.py", line 1109, in exec_module
    summary_data = module.main(command[2:], self)
  File "/home/eth/tools/pacu/modules/iam__bruteforce_permissions/main.py", line 331, in main
    current_client = pacu_main.get_boto3_client(service, region)
  File "pacu.py", line 1508, in get_boto3_client
    config=boto_config
  File "/home/eth/tools/pacu/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/eth/tools/pacu/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/eth/tools/pacu/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/home/eth/tools/pacu/botocore/client.py", line 70, in create_client
    cls = self._create_client_class(service_name, service_model)
  File "/home/eth/tools/pacu/botocore/client.py", line 95, in _create_client_class
    base_classes=bases)
  File "/home/eth/tools/pacu/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/home/eth/tools/pacu/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/home/eth/tools/pacu/boto3/utils.py", line 61, in _handler
    module = import_module(module)
  File "/home/eth/tools/pacu/boto3/utils.py", line 52, in import_module
    __import__(name)
  File "/home/eth/tools/pacu/boto3/s3/inject.py", line 15, in <module>
    from boto3.s3.transfer import create_transfer_manager
  File "/home/eth/tools/pacu/boto3/s3/transfer.py", line 129, in <module>
    from s3transfer.manager import TransferConfig as S3TransferConfig
  File "/home/eth/.local/lib/python3.6/site-packages/s3transfer/manager.py", line 21, in <module>
    from s3transfer.utils import get_callbacks
  File "/home/eth/.local/lib/python3.6/site-packages/s3transfer/utils.py", line 27, in <module>
    from botocore.exceptions import ReadTimeoutError
<class 'ImportError'>: cannot import name 'ReadTimeoutError'
```

**Operating System (please complete the following information):**
 - Python version: Python 3.6.8

**Comment by SpenGietz** [comment]
Looks like it's because Pacu uses an old version of the botocore/boto3 libraries but not the s3transfer library, so the latest version of s3transfer is trying to import something that doesn't yet exist in botocore.

Because of the reliance on the old version of boto3/botocore, I don't think this will be an easy fix, but I'll see what I can do

**Comment by SpenGietz** [comment]
Fixed in this PR: https://github.com/RhinoSecurityLabs/pacu/pull/167

Will close this when it's merged to master

**Comment by SpenGietz** [comment]
Fixed!
