### ISSUE TITLE
iam__enum_permissions crashes if a policy has no Resource key

### ISSUE THREAD

**Issue by SpenGietz** [RhinoSecurityLabs/pacu#183]
```
Traceback (most recent call last):
  File "pacu.py", line 1561, in run_gui
    self.idle()
  File "pacu.py", line 1441, in idle
    self.idle()
  File "pacu.py", line 1441, in idle
    self.idle()
  File "pacu.py", line 1441, in idle
    self.idle()
  [Previous line repeated 1 more time]
  File "pacu.py", line 1439, in idle
    self.parse_command(command)
  File "pacu.py", line 463, in parse_command
    self.parse_exec_module_command(command)
  File "pacu.py", line 585, in parse_exec_module_command
    self.exec_module(command)
  File "pacu.py", line 859, in exec_module
    summary_data = module.main(command[2:], self)
  File "/pacu/modules/iam__enum_permissions/main.py", line 275, in main
    role = parse_attached_policies(client, attached_policies, role)
  File "/pacu/modules/iam__enum_permissions/main.py", line 523, in parse_attached_policies
    user = parse_document(document, user)
  File "/pacu/modules/iam__enum_permissions/main.py", line 670, in parse_document
    if isinstance(statement['Resource'], list):
<class 'KeyError'>: 'Resource'
```

**Comment by DaveYesland** [comment]
Fixed in #225
