### ISSUE TITLE
China region not added?

### ISSUE THREAD

**Issue by AFV-Aon** [RhinoSecurityLabs/pacu#192]
Tried to update the regions through the latest version of botocore, but cn-north-1 and cn-northwest-1 are not there. 

Is there a way to manually add the region to the session? Some modules fail because there is no --region attribute on them.

Thanks!

**Comment by seb1055** [comment]
Hi, have you tried running the command ```update_regions``` from Pacu cli? This will attempt to update boto to the latest version and query available regions/endpoints. Once this is done you can view the imported regions with the ```regions``` command. Additionally, you will also need to meet the AWS requirements to access these regions as documented [here](https://aws.amazon.com/blogs/enterprise-strategy/getting-started-with-aws-services-in-aws-china-beijing-region-and-aws-china-ningxia-region/#:~:text=AWS%20China%20Regions%20names%20are,is%20amazonaws.com.cn.). 👍

**Comment by AFV-Aon** [comment]
I tried using update_regions command inside pacu framework (I don't think that command works on CLI?), however China region just doesn't show up.

**Comment by seb1055** [comment]
To confirm the credentials you are using have access to those regions? For those regions, you need an account specifically registered in/by China. Accounts registers outside won't have access to those endpoints.

**Comment by AFV-Aon** [comment]
Yes, the account is hosted on cn-north-1 and cn-northwest-1 (confirmed via AWS console). It's just that update_regions doesn't add those 2 regions.

**Comment by seb1055** [comment]
Thanks for the additional information. Taking a look at the update_regions() function [here](https://github.com/RhinoSecurityLabs/pacu/blob/b345370df18ed4148bf2d2184192c773d7d832e0/pacu.py#L666) and I see it is pulling the regions from the file ./botocore/data/endpoints.json and writing them to the file modules/service_regions.json. While I am not sure why your botocore file does not include these regions I found a reference to the format [here ](https://github.com/boto/botocore/blob/9f538190dbb425902b7757b6a9a5998fc0c4106c/botocore/data/endpoints.json#L6071). It might be possible to add they regions manually but, I don't have an account with access to those regions to verify.

**Comment by AFV-Aon** [comment]
I modified pacu.py update_regions() function manually and added 'aws-cn':

Line 694: if partition['partition'] == 'aws' or partition['partition'] == 'aws-cn':

This actually breaks things like the list command:

Pacu (schelec3:No Keys Set) > list

[2020-07-27 11:35:58] Pacu encountered an error while running the previous command. Check sessions/xxx/error_log.txt for technical details. [LOG LEVEL: MINIMAL]

    <class 'KeyError'>: 'inspector'

Traceback (most recent call last):
  File "pacu.py", line 1561, in run_gui
    self.idle()
  File "pacu.py", line 1441, in idle
    self.idle()
  File "pacu.py", line 1441, in idle
    self.idle()
  File "pacu.py", line 1441, in idle
    self.idle()
  [Previous line repeated 1 more time]
  File "pacu.py", line 1439, in idle
    self.parse_command(command)
  File "pacu.py", line 457, in parse_command
    self.parse_list_command(command)
  File "pacu.py", line 578, in parse_list_command
    self.list_modules('')
  File "pacu.py", line 985, in list_modules
    regions += self.get_regions(service)
  File "pacu.py", line 220, in get_regions
    if type(regions[service]) == dict and regions[service].get('endpoints'):
<class 'KeyError'>: 'inspector'


It would be good to try and fix this code so the china region can be successfully added to a session.

Thanks!

**Comment by zhujian0805** [comment]
any update for this issue?

**Comment by zhujian0805** [comment]
Created a PR for this issue:
https://github.com/RhinoSecurityLabs/pacu/pull/307
