### ISSUE TITLE
module cloudwatch__download_logs error

### ISSUE THREAD

**Issue by naikordian** [RhinoSecurityLabs/pacu#212]
```console
Pacu (lambda:imported-default) > run cloudwatch__download_logs
  Running module cloudwatch__download_logs...
[cloudwatch__download_logs] Enumerating ap-northeast-1...
[cloudwatch__download_logs]   No Log Groups found
[cloudwatch__download_logs] Enumerating ap-northeast-2...
[cloudwatch__download_logs]   No Log Groups found
[cloudwatch__download_logs] Enumerating ap-south-1...
[cloudwatch__download_logs]   No Log Groups found
[cloudwatch__download_logs] Enumerating ap-southeast-1...
[cloudwatch__download_logs]   1 Log Groups found

[2020-11-05 03:39:34] Pacu encountered an error while running the previous command. Check sessions/ec2/error_log.txt for technical details. [LOG LEVEL: MINIMAL]

    <class 'TypeError'>: describe_log_streams() only accepts keyword arguments.
```
```console
➜  ec2 git:(master) ✗ cat error_log.txt
[2020-11-05 03:39:34] (ec2):
Traceback (most recent call last):
  File "pacu.py", line 1607, in run_gui
    traceback_text = '\nTraceback (most recent call last):\n{}{}: {}\n\n'.format(''.join(traceback.format_tb(tb)), str(exception_type), str(exception_value))
  File "pacu.py", line 1487, in idle
    service = arg.data
  File "pacu.py", line 1487, in idle
    service = arg.data
  File "pacu.py", line 1487, in idle
    service = arg.data
  [Previous line repeated 28 more times]
  File "pacu.py", line 1485, in idle
    session = arg.session
  File "pacu.py", line 467, in parse_command
    self.parse_search_command(command)
  File "pacu.py", line 606, in parse_exec_module_command
    if command[1] in ('cat', 'category'):
  File "pacu.py", line 879, in exec_module
    except SystemExit as error:
  File "/home/ubuntu/tools/pacu/modules/cloudwatch__download_logs/main.py", line 128, in main
    streams = collect_all(
  File "/home/ubuntu/tools/pacu/modules/cloudwatch__download_logs/main.py", line 84, in collect_all
    response = caller({'nextToken': response['nextToken'], **kwargs})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/client.py", line 354, in _api_call
    raise TypeError(
<class 'TypeError'>: describe_log_streams() only accepts keyword arguments.
```
OS : WSL Ubuntu 20.04.1 LTS
Python: 3.8.5

**Comment by rcha0s** [comment]
Seeing the same issue with this module.

**Comment by naikordian** [comment]
@sebastian-mora Do you still work on this issue? If you don't mind maybe I can fix this.
