### ISSUE TITLE
<class 'KeyError'>: 'Contents'

### ISSUE THREAD

**Issue by Techbrunch** [RhinoSecurityLabs/pacu#234]
When running the iam__bruteforce_permissions module we ran into the following issue:

```
[iam__bruteforce_permissions] ---------------------------------------------------------
[iam__bruteforce_permissions] Trying get_object...
[iam__bruteforce_permissions] Kwargs: {'Key': 'dummy_data', 'Bucket': 'dummy_data'}
ClientError: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
  Special Parameter Found
      Found special param
Getting info for func: get_object, param: Key

[2021-03-15 13:37:42] Pacu encountered an error while running the previous command. Check sessions/REDACTED/error_log.txt for technical details. [LOG LEVEL: MINIMAL]

    <class 'KeyError'>: 'Contents'
```

```
[2021-03-15 13:37:42] (REDACTED):
Traceback (most recent call last):
  File "/opt/pacu/pacu.py", line 1648, in run_gui
    self.idle()
  File "/opt/pacu/pacu.py", line 1529, in idle
    self.idle()
  File "/opt/pacu/pacu.py", line 1529, in idle
    self.idle()
  File "/opt/pacu/pacu.py", line 1529, in idle
    self.idle()
  [Previous line repeated 5 more times]
  File "/opt/pacu/pacu.py", line 1527, in idle
    self.parse_command(command)
  File "/opt/pacu/pacu.py", line 599, in parse_command
    self.parse_exec_module_command(command)
  File "/opt/pacu/pacu.py", line 731, in parse_exec_module_command
    self.exec_module(command)
  File "/opt/pacu/pacu.py", line 937, in exec_module
    summary_data = module.main(command[2:], self)
  File "/opt/pacu/modules/iam__bruteforce_permissions/main.py", line 356, in main
    elif exception_handler(func, kwargs, error):
  File "/opt/pacu/modules/iam__bruteforce_permissions/main.py", line 262, in exception_handler
    if not convert_special_params(func, kwargs):
  File "/opt/pacu/modules/iam__bruteforce_permissions/main.py", line 190, in convert_special_params
    kwargs[param] = param_generator.get_special_param(current_client, func, param)
  File "/opt/pacu/modules/iam__bruteforce_permissions/param_generator.py", line 18, in get_special_param
    PARAM_CACHE[param] = get_key(client)
  File "/opt/pacu/modules/iam__bruteforce_permissions/param_generator.py", line 25, in get_key
    key = client.list_objects_v2(
<class 'KeyError'>: 'Contents'
```

**Comment by Techbrunch** [comment]
@RyanJarv FYI, I ended up using [enumerate-iam](https://github.com/andresriancho/enumerate-iam) which is extracting the API calls by parsing the `aws-sdk-js` library documentation.

**Comment by RyanJarv** [comment]
@Techbrunch Thanks for letting me know. I was actually looking into that project before, thinking it may make sense to replace this module with that at some point.

For now I believe this should be fixed though, if you have time and still want to test out the recent changes in master let me know how it works for you.
