### ISSUE TITLE
AWS Cloudshell integration - ignore access key missing?

### ISSUE THREAD

**Issue by GarnetSunset** [RhinoSecurityLabs/pacu#266]
Hey there, trying to run pacu in an environment I help manage, noticing that when I try to run it it complains about no access key etc etc, cloudshell does NOT require an access key, due to it because given special privileges, it seems this issue was faced by the guys who work on prowler too, but their fix for it was checking for an ENV variable and skipping the check, could that be implemented here?
Thanks!

https://github.com/toniblyx/prowler/commit/de3e2c3a2bb34aaeb8fab869da2840d7b2b4ef45

**Comment by GarnetSunset** [comment]
https://github.com/GarnetSunset/pacu/commit/31d992d8ff4bc8739e84452c85f6faea08aff288

**Comment by RyanJarv** [comment]
So I think the `use_env_creds` option I added to https://github.com/RhinoSecurityLabs/pacu/tree/features/use-env-creds will handle this. At the moment I'm mostly debating if this should be default in Pacu before it get's merged, but if you want to test that out and see if it works for this use case you just need to make sure to run `use_env_creds` after startup.

**Comment by GarnetSunset** [comment]
I've been trying to run "cli.py" from that fork, not sure if 'm messing this up.

```    Exception raised: (sqlite3.OperationalError) no such column: pacu_session.RDS
[SQL: SELECT pacu_session.id AS pacu_session_id, pacu_session.created AS pacu_session_created, pacu_session.is_active AS pacu_session_is_active, pacu_session.name AS pacu_session_name, pacu_session.boto_user_agent AS pacu_session_boto_user_agent, pacu_session.key_alias AS pacu_session_key_alias, pacu_session.access_key_id AS pacu_session_access_key_id, pacu_session.secret_access_key AS pacu_session_secret_access_key, pacu_session.session_token AS pacu_session_session_token, pacu_session.session_regions AS pacu_session_session_regions, pacu_session."APIGateway" AS "pacu_session_APIGateway", pacu_session."CloudTrail" AS "pacu_session_CloudTrail", pacu_session."CloudWatch" AS "pacu_session_CloudWatch", pacu_session."CodeBuild" AS "pacu_session_CodeBuild", pacu_session."Config" AS "pacu_session_Config", pacu_session."DataPipeline" AS "pacu_session_DataPipeline", pacu_session."DynamoDB" AS "pacu_session_DynamoDB", pacu_session."EC2" AS "pacu_session_EC2", pacu_session."ECS" AS "pacu_session_ECS", pacu_session."Glue" AS "pacu_session_Glue", pacu_session."GuardDuty" AS "pacu_session_GuardDuty", pacu_session."IAM" AS "pacu_session_IAM", pacu_session."Inspector" AS "pacu_session_Inspector", pacu_session."Lambda" AS "pacu_session_Lambda", pacu_session."Lightsail" AS "pacu_session_Lightsail", pacu_session."S3" AS "pacu_session_S3", pacu_session."SecretsManager" AS "pacu_session_SecretsManager", pacu_session."SSM" AS "pacu_session_SSM", pacu_session."Shield" AS "pacu_session_Shield", pacu_session."VPC" AS "pacu_session_VPC", pacu_session."WAF" AS "pacu_session_WAF", pacu_session."WAFRegional" AS "pacu_session_WAFRegional", pacu_session."Account" AS "pacu_session_Account", pacu_session."AccountSpend" AS "pacu_session_AccountSpend", pacu_session."Route53" AS "pacu_session_Route53", pacu_session."RDS" AS "pacu_session_RDS" 
FROM pacu_session 
WHERE pacu_session.is_active = 1]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: pacu_session.RDS```

**Comment by GarnetSunset** [comment]
Figured it out, turns out the database wasnt compatible with the version on pip, might be something worth looking into

**Comment by RyanJarv** [comment]
Yeah that's a known issue, I just opened up #272 for it since that's overdo to get fixed. Glad to hear you got it working though, I think I'll go ahead and try to get that merged into master sometime soon, being able to use the default credential lookup behavior is definitely useful when you need it.

**Comment by RyanJarv** [comment]
On the credential lookup issues I'm going to close this in favor of #266.
