### ISSUE TITLE
Need support for Assumed Role

### ISSUE THREAD

**Issue by jchrisfarris** [RhinoSecurityLabs/pacu#27]
I've assumed a SAML role that is tied to my corp AD. I entered the key id, secret and session token. Attempting to confirm permissions results in this error:

```
Pacu (mysession) > run confirm_permissions
    Running module confirm_permissions...
      This module will attempt to use IAM APIs to enumerate a confirmed list of IAM permissions for the current user. This is done by checking attached and inline policies for the user and the groups they are in.

[2018-07-14 19:48:50] Pacu encountered an error while running the previous command. Check sessions/mysession/error_log.txt for technical details. [LOG LEVEL: MINIMAL]

    <class 'botocore.exceptions.ClientError'>: An error occurred (ValidationError) when calling the GetUser operation: Must specify userName when calling with non-User credentials
```

Error in the Log file is:
```
[2018-07-14 19:39:40] (mysession): 
Traceback (most recent call last):
  File "pacu.py", line 1394, in run
    self.idle()
  File "pacu.py", line 1303, in idle
    self.idle()
  File "pacu.py", line 1303, in idle
    self.idle()
  File "pacu.py", line 1303, in idle
    self.idle()
  [Previous line repeated 2 more times]
  File "pacu.py", line 1301, in idle
    self.parse_command(command)
  File "pacu.py", line 693, in parse_command
    self.exec_module(command)
  File "pacu.py", line 866, in exec_module
    module.main(command[2:], self)
  File "/Users/chrisfarris/InfoSec/pacu/modules/confirm_permissions/main.py", line 85, in main
    user = client.get_user()
  File "/Users/chrisfarris/InfoSec/pacu/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/chrisfarris/InfoSec/pacu/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
<class 'botocore.exceptions.ClientError'>: An error occurred (ValidationError) when calling the GetUser operation: Must specify userName when calling with non-User credentials
```
Basic issue is that my keys are not tied to an IAM User. They're tied to a role which I assumed via federated identity. This is probably also the case when using Instance Profile keys. 

The AWS call `aws sts get-caller-identity` should probably be called first to determine what form of identity the keys I've obtained are:
```
Patton:pacu chrisfarris$ aws sts get-caller-identity --profile myprofile
{
    "Account": "530000000074",
    "UserId": "AROACENSORED:first.last@company.com",
    "Arn": "arn:aws:sts::530000000074:assumed-role/my-company-role-name/first.last@company.com"
}
```
note the "assumed-role in the arn above.

**Comment by SpenGietz** [comment]
Merged into master! Both `iam__enum_permissions` and `iam__privesc_scan` were updated with role support
