### ISSUE TITLE
Console not working

### ISSUE THREAD

**Issue by random-robbie** [RhinoSecurityLabs/pacu#275]
running docker latest version i am getting the following error when running console

```
[2021-06-24 14:33:43] (y): 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pacu/main.py", line 1666, in run_gui
    self.idle()
  File "/usr/local/lib/python3.9/site-packages/pacu/main.py", line 1548, in idle
    self.idle()
  File "/usr/local/lib/python3.9/site-packages/pacu/main.py", line 1548, in idle
    self.idle()
  File "/usr/local/lib/python3.9/site-packages/pacu/main.py", line 1548, in idle
    self.idle()
  [Previous line repeated 5 more times]
  File "/usr/local/lib/python3.9/site-packages/pacu/main.py", line 1546, in idle
    self.parse_command(command)
  File "/usr/local/lib/python3.9/site-packages/pacu/main.py", line 596, in parse_command
    self.print_web_console_url()
  File "/usr/local/lib/python3.9/site-packages/pacu/main.py", line 831, in print_web_console_url
    res = sts.get_federation_token(  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 677, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 725, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/usr/local/lib/python3.9/site-packages/botocore/validate.py", line 319, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
<class 'botocore.exceptions.ParamValidationError'>: Parameter validation failed:
Invalid length for parameter Name, value: 1, valid min length: 2

```

**Comment by RyanJarv** [comment]
Hi there! So it looks like AWS is complaining about the name you set for the key alias being to short.

We should be able to work around this in a future update but for now I'd recommend making the key alias name longer. Should be able to change this with set_keys, entering a different name and just pressing enter for the rest of the prompts.

Let me know if you are still having issues after this change.
