### ISSUE TITLE
Install on Ubuntu 22.04 missing dependency policyuniverse

### ISSUE THREAD

**Issue by SDDunt** [RhinoSecurityLabs/pacu#362]
$ ./cli.py      
Traceback (most recent call last):                  
  File "/home/sdunt/Documents/AWS/pacu/./cli.py", line 15, in <module>
    sys.exit(main())                                
  File "/home/sdunt/Documents/AWS/pacu/./cli.py", line 11, in main
    pacu.Main().run()                               
  File "/home/sdunt/Documents/AWS/pacu/pacu/main.py", line 186, in __init__
    self.CATEGORIES: set = load_categories()        
  File "/home/sdunt/Documents/AWS/pacu/pacu/main.py", line 65, in load_categories
    module = __import__(module_path, globals(), locals(), ['module_info'], 0)
  File "/home/sdunt/Documents/AWS/pacu/pacu/modules/iam__enum_permissions/main.py", line 7, in <module>
    from policyuniverse.statement import Statement  
ModuleNotFoundError: No module named 'policyuniverse'

$ python3 cli.py
Traceback (most recent call last):                  
  File "/home/sdunt/Documents/AWS/pacu/cli.py", line 15, in <module>
    sys.exit(main())                          
  File "/home/sdunt/Documents/AWS/pacu/cli.py", line 11, in main
    pacu.Main().run()
  File "/home/sdunt/Documents/AWS/pacu/pacu/main.py", line 186, in __init__
    self.CATEGORIES: set = load_categories()
  File "/home/sdunt/Documents/AWS/pacu/pacu/main.py", line 65, in load_categories
    module = __import__(module_path, globals(), locals(), ['module_info'], 0)
  File "/home/sdunt/Documents/AWS/pacu/pacu/modules/iam__enum_permissions/main.py", line 7, in <module>
    from policyuniverse.statement import Statement
ModuleNotFoundError: No module named 'policyuniverse'

$ python3 pip install policyuniverse
python3: can't open file '/home/sdunt/Documents/AWS/pacu/pip': [Errno 2] No such file or directory
2 sdunt@PPI-A2964:~/Documents/AWS/pacu$ pip3 install policyuniverse                                       
Defaulting to user installation because normal site-packages is not writeable
Collecting policyuniverse
  Downloading policyuniverse-1.5.1.20230608-py2.py3-none-any.whl (462 kB)
     |████████████████████████████████| 462 kB 4.1 MB/s 
Installing collected packages: policyuniverse
Successfully installed policyuniverse-1.5.1.20230608 

And NOW it will run.

p.s. there were no errors on the bash install.sh step..

**Comment by DaveYesland** [comment]
This should be fixed now policyuniverse was missing from requirements.txt.
Also you can install Pacu with `pip install pacu` now as well.
